#! /bin/sh

if test x"${PHP_5}" = x"" ; then
	PHP_5="php"
fi

dir=`dirname "$0"`
if test -d "$dir/platform" && test -f "$dir/platform/platform.php" ; then
	true
elif test -d ./platform ; then
	dir=`pwd`
fi
cd "$dir"

if test -r index.php ; then
	exec ${PHP_5} -f index.php "$@"
fi

if test -r platform/index.setup.php ; then
	echo ">>> index.php does not exist, running 'eregansu setup'" >&2
	exec ${PHP_5} -f platform/index.setup.php
fi

echo "$0: cannot find index.php or platform/index.setup.php" >&2
exit 1
