<!DOCTYPE html>
<html>
<!--
  Copyright 2011 Mo McRoberts.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License. 
-->
  <head>
	<meta charset="UTF-8">
	<title>RDF Parser Example</title>
	<link rel="stylesheet" href="screen.css" type="text/css">
  </head>
  <body>
	<article>
	  <section>
		<h1>RDF Parser Example</h1>
		<form method="get" action="rdfparse.php">
		  <input type="text" name="url" value="<?php e(@$request->query['url']);?>" size="40">
		  <input type="submit">
		</form>
	  </section>
	<?php if(isset($doc)) { ?>
	<hr>
	<section>
	  <h2>RDF/XML</h2>
	  <pre><?php
$r = $doc->asXML();
e(is_array($r) ? implode("\n", $r) : $r);
?>
	  </pre>
	</section>
	<hr>
	<section>
	  <h2>Turtle</h2>
	  <pre><?php
$r = $doc->asTurtle();
e(is_array($r) ? implode("\n", $r) : $r);
?>
	  </pre>
	</section>
	<hr>
	<section>
	  <h2>RDF/JSON</h2>
	  <pre><?php
$r = $doc->asJSON();
e(is_array($r) ? implode("\n", $r) : $r);
?>
	  </pre>
	</section>
	<hr>
	<section>
	  <h2>RDFDocument object</h2>
	  <pre><?php
ob_start();
print_r($doc);
e(ob_get_clean());
?>
	  </pre>
	</section>
	<?php } ?>
	</article>
	<footer>
	  <p>Copyright &copy; 2011 Mo McRoberts.</p>
	</footer>
  </body>
</html>
