<?php

/* Copyright 2010 Mo McRoberts.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. The names of the author(s) of this software may not be used to endorse
 *    or promote products derived from this software without specific prior
 *    written permission.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, 
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY 
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL
 * AUTHORS OF THIS SOFTWARE BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

class Installer
{
	public $appname;
	public $appconfig;
	public $appconfigCreated;

	public function __construct()
	{
	}
	
	public function run()
	{
		$this->init();
		$this->checkConfigRoot();
		$this->checkAppName();
		$this->checkAppConfig();
		$this->checkAppConfigLink();
		
		/* Once this class has been finished, we should return true */
	}
	
	protected function init()
	{
		echo "Eregansu Setup\n";
		echo "==============\n\n";
		
		echo "This script will generate an initial set of configuration files for your\n";
		echo "application based upon the answers you give below.\n\n";

		echo "Files will be stored in the following locations:\n\n";

		echo " - Instance root:       " . INSTANCE_ROOT . "\n";
		echo " - Application modules: " . INSTANCE_ROOT . "app/\n";
		echo " - Configuration files: " . CONFIG_ROOT . "\n";
		echo " - Eregansu platform:   " . PLATFORM_ROOT . "\n";
		echo "\n";
	}
	
	protected function checkConfigRoot()
	{
		if(file_exists(CONFIG_ROOT))
		{
			echo "--> " . CONFIG_ROOT . " already exists.\n\n";
		}
		else
		{
			echo "--> " . CONFIG_ROOT . " does not exist, creating.\n\n";
			if(!mkdir(CONFIG_ROOT)) exit(1);
		}
	}
	
	protected function checkAppName()
	{
		echo "\nYou need to specify a short name for your application. This name will be used\n";
		echo "in the filename of your application configuration file. For example, if you\n";
		echo "set the short name to be 'myapp', the application configuration file will be\n";
		echo "created as appconfig.myapp.php. A symbolic link will be created from this file\n";
		echo "to appconfig.php.\n\n";
		
		do
		{
			echo "Please enter a name consisting only of letters, numbers and dashes, 1-16 characters\n";
			$this->appname = $this->prompt('Application name', 'default');
			if(strlen($this->appname) < 1 || strlen($this->appname) > 16) continue;
			if(!preg_match('/^[A-Za-z0-9-]+$/', $this->appname)) continue;
			break;
		}
		while(true);
		echo "\n";
	}
	
	protected function checkAppConfig()
	{
		$this->appconfig = CONFIG_ROOT . 'appconfig.' . $this->appname . '.php';				
		if(file_exists($this->appconfig))
		{
			echo "The file appconfig." . $this->appname . ".php already exists. Would you like to delete it\n";
			echo "and create a new one?\n\n";
			do
			{
				$ans = $this->prompt("Delete appconfig." . $this->appname . ".php", 'N', 'Y/N');
				$ans = substr(strtoupper($ans), 0, 1);
				if($ans == 'Y' || $ans == 'N') break;
			}
			while(true);
			echo "\n";
			if($ans == 'Y')
			{
				echo "--> Deleting existing " . $this->appconfig . "\n";
				if(!unlink($this->appconfig)) exit(1);
			}
		}
		if(file_exists($this->appconfig))
		{
			echo "--> Skipping application configuration as appconfig." . $this->appname . ".php already exists\n";
		}
		else
		{
			$this->appconfigCreated = true;
			echo "--> Creating " . $this->appconfig . "\n";
			if(!($f = fopen($this->appconfig, 'w'))) exit(1);
			fwrite($f, '<?php' . "\n\n");
			fwrite($f, '/* Application configuration for ' . $this->appname . ' - generated by Eregansu Setup at ' . strftime('%Y-%m-%d %H:%M:%S') . '*/' . "\n\n");
			fclose($f);
		}
	}
	
	protected function checkAppConfigLink()
	{
		if(file_exists(CONFIG_ROOT . 'appconfig.php'))
		{
			if(is_link(CONFIG_ROOT . 'appconfig.php'))
			{
				echo "--> appconfig.php already exists and is a symbolic link, re-creating\n";
				if(!unlink(CONFIG_ROOT . 'appconfig.php')) exit(1);
			}
			else
			{
				echo "The file appconfig.php already exists but is not a symbolic link. Do you\n";
				echo "wish to keep this file as-is, or move it out of the way and create the symbolic\n";
				echo "link to appconfig." . $this->appname . ".php?\n\n";
				do
				{
					$ans = $this->prompt("Keep appconfig.php as-is", 'N', 'Y/N');
					$ans = substr(strtoupper($ans), 0, 1);
					if($ans == 'Y' || $ans == 'N') break;
				}
				while(true);
				if($ans == 'N')
				{
					$newname = "appconfig.old-" . getmypid() . ".php";
					echo "---> Renaming appconfig.php to $newname\n";
					if(!rename(CONFIG_ROOT . 'appconfig.php', CONFIG_ROOT . $newname)) exit(1);
				}
			}
		}
		if(!file_exists(CONFIG_ROOT . 'appconfig.php'))
		{
			chdir(CONFIG_ROOT);
			echo "--> Symbolically linking appconfig." . $this->appname . ".php to appconfig.php\n";
			symlink('appconfig.' . $this->appname . '.php', 'appconfig.php');
		}
		echo "\n";	
	}
	
	
	protected function prompt($prompt, $default = null, $options = null)
	{
		static $stdin;
		
		if(!$stdin)
		{
			$stdin = fopen('php://stdin', 'r');
		}
		if($options)
		{
			$prompt .= ' (' . $options . ')';
		}
		$prompt .= '?';
		if($default)
		{
			$prompt .= ' [' . $default . '] ';
		}
		echo $prompt;
		flush();
		$line = trim(fgets($stdin));
		if(!strlen($line) && $default)
		{
			$line = $default;
		}
		echo "\n";
		flush();
		return $line;
	}
}

$installer = new Installer();

if(!$installer->run())
{
	exit(1);
}

